geo_portal/geo_portal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('map.urls', namespace = 'map')),
    path('admin/', admin.site.urls),
]

geo_portal/layers/urls.py
from django.urls import path
from layers import views

app_name = 'layers'

geo_portal/map/urls.py
from django.urls import path
from map import views

app_name = 'map'

urlpatterns = [
    path('',views.MapTemplateView.as_view(), name = 'map'),
    path('layers/', views.layers_dataset, name = 'layers'),
    path('categories/', views.categories_dataset, name = 'categories'),
]

geo_portal/layers/models.py
from django.contrib.gis.db import models

# Create your models here.
class LayersCategory(models.Model):
    name = models.CharField(unique=True, max_length=200)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Categories'

class Layers(models.Model):
    layers_category = models.ForeignKey(LayersCategory, on_delete=models.CASCADE, related_name='categories')
    name = models.CharField(unique=True, max_length=200)
    geom = models.GeometryCollectionField()

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Layers'

geo_portal/map/models.py
from django.db import models

# Create your models here.

geo_portal/layers/views.py
from django.shortcuts import render

# Create your views here.

geo_portal/map/views.py
from django.shortcuts import render
from django.views.generic import (View, TemplateView,ListView)
from django.core.serializers import serialize
from django.http import HttpResponse
from layers import models
# Create your views here.


class MapTemplateView(TemplateView):
    template_name = 'map/index.html'

def layers_dataset(request):
    layers = serialize('geojson', models.Layers.objects.all())
    return HttpResponse(layers)

def categories_dataset(request):
    categories = serialize('geojson', models.LayersCategory.objects.all())
    return HttpResponse(categories)

geo_portal/map/templates/map/index.html
<!DOCTYPE html>
{% load staticfiles %}
{% load leaflet_tags %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Create your map</title>
    {% leaflet_js %}
    {% leaflet_css %}

    <link rel="stylesheet" href="{% static 'my_style/map.css' %}">
    <link rel="stylesheet" href="{% static 'my_style/leaflet.groupedlayercontrol.css' %}">
    <script type="text/javascript" src="{% static 'dist/leaflet.ajax.js' %}"></script>
    <script type="text/javascript" src="{% static 'dist/leaflet.groupedlayercontrol.js' %}"></script>

  </head>
  <body>
    <h1>Navigation</h1>
      <script type="text/javascript">
        function map_layers(map, options){
          var osm = L.tileLayer('http://{s}.tile.openstreetmap.org/{z}{y}{x}.png');
          // var layers = new L.GeoJSON.AJAX("{% url 'map:layers' %}",{
          //   onEachFeature: function(feature,layer){
          //     layer.bindPopup(feature.properties.name.toString());
          //   }
          // });
          var layers = new L.GeoJSON.AJAX("{% url 'map:layers' %}");
          layers.addTo(map);

          // var categories = new L.GeoJSON.AJAX("{% url 'map:categories' %}")
          var baseLayers = {
            "OSM": osm
          }

          var groupedOverlays = {
            "Layers": {
              "layers": layers,
            }
          };

          L.control.groupedLayers(baseLayers, groupedOverlays).addTo(map);
        }
      </script>
      {% leaflet_map "citymap" callback="window.map_layers" %}
  </body>
</html>